#
# Build and push PostHog and PostHog Cloud container images
#
# - posthog_build: build and push the PostHog container image to DockerHub
#
# - posthog_cloud_build: build the PostHog Cloud container image using
#   as base image the container image from the previous step. The image is
#   then pushed to AWS ECR.
#
name: Container Images CD

on:
    push:
        branches:
            - ubicloud-runner
    workflow_dispatch:

jobs:
    posthog_build:
        strategy:
          matrix:
            runs-on: [ubuntu-latest, ubicloud-standard-2-arm]
        continue-on-error: true
        name: ${{matrix.runs-on}}
        runs-on: ${{matrix.runs-on}}

        steps:
            - name: Check out
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Update git SHA
              run: echo "GIT_SHA = '${GITHUB_SHA}'" > posthog/gitsha.py

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Build and push container image
              id: build
              uses: docker/build-push-action@v5
              with:
                  push: false
                  tags: posthog/posthog:${{ github.sha }},posthog/posthog:latest
                  platforms: linux/arm64
                  build-args: COMMIT_HASH=${{ github.sha }}
